# Author: Noel McKeown (TUD)
# Student Number: x00218705
# Date: Dec-2024
# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.

name: Build and deploy BP Calculator ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: ca1app             # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'  # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6'                   # set this to the .NET Core version to use
  URI: https://ca1app.azurewebsites.net/    

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  provision_staging:
    name: Provision Staging Infra
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # JSON objects which represents service principal

      #- run: |
      #    az webapp list --query "[?state=='Running']"

      
      # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./IaC/template.json
          parameters: ./IaC/staging.parameter.json

      # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}