name: Test Profile

env:
  AZURE_PROD_WEBAPP_NAME: prod-ca1app               # prod webapp
  AZURE_STAGING_WEBAPP_NAME: staging-ca1app        # staging webapp
  AZURE_RESOURCE_GROUP: ca1rg
  AZURE_SUB: 9ec68712-3805-4cf9-a4c1-4e5951df302b
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project, defaults to the repository root
  E2E_STAGING_FILE: 'SeleniumTest.staging.runsettings'
  E2E_PROD_FILE: 'SeleniumTest.prod.runsettings'
  DOTNET_VERSION: '6'                               # set this to the .NET Core version to use
  PROD_URI: https://ca1app.azurewebsites.net/    

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # deploy code to webapp service
  test_profile:
    name: Deploy Feature to Staging
    needs: deploy_staging
    permissions:
      contents: none
      issues: write
    runs-on: ubuntu-latest

    steps:    
      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # get publishing profile for newly provisioned staging environment
      - name: Get Publish Profile
        run: |
          echo "PublishProfile<<EOF" >> $GITHUB_ENV
          az webapp deployment list-publishing-credentials --name ${{env.AZURE_STAGING_WEBAPP_NAME}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{env.AZURE_SUB}} >> $GITHUB_ENV
          az webapp deployment list-publishing-credentials --name ${{env.AZURE_STAGING_WEBAPP_NAME}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{env.AZURE_SUB}} >> profile.json
          cat profile.json
          echo "EOF" >> $GITHUB_ENV
          echo "PublishProfile=$PublishProfile"
          echo "GITHUB_ENV=$GITHUB_ENV"