name: Test Jobs

env:
  AZURE_PROD_WEBAPP_NAME: prod-ca1app               # prod webapp
  AZURE_STAGING_WEBAPP_NAME: staging-ca1app        # staging webapp
  AZURE_RESOURCE_GROUP: ca1rg
  AZURE_SUB: 9ec68712-3805-4cf9-a4c1-4e5951df302b
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project, defaults to the repository root
  E2E_STAGING_FILE: 'SeleniumTest.staging.runsettings'
  E2E_PROD_FILE: 'SeleniumTest.prod.runsettings'
  DOTNET_VERSION: '6'                               # set this to the .NET Core version to use
  PROD_URI: https://ca1app.azurewebsites.net/    

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # build feature branch
  build_feature:
    name: Build Feature Branch
    if: true
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4
        with:
          ref: pulse-pressure-feature

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set Up Dependency Caching
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # build app
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # run unit tests
      - name: Run UNIT Tests
        run: |
          dotnet test BPCalcUnit/BPCalcUnitTests.csproj --collect "XPlat Code Coverage"
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"./BPCalcUnit/TestResults/*/coverage.cobertura.xml" -targetdir:"./BPCalcUnit/coverage-report" -reporttypes:Html

      # publish artifact
      - name: dotnet Publish
        run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

      # upload build artifact for deploy job
      - name: Upload artifact for Deployment Job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app-feature
          path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

  # provision staging environment
  provision_staging:
    name: Provision Staging Infra
    if: false
    #needs: owasp_dependency_check
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
      - name: Provision Staging
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./IaC/webapp.template.json
          parameters: sites_ca1app_name=${{ env.AZURE_STAGING_WEBAPP_NAME }}

  build:
    name: Build & Test
    if: true
    runs-on: windows-latest
    #needs: provision_staging

    steps:
      - uses: actions/checkout@v4   

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set Up Dependency Caching
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # build app
      - name: Build with dotnet
        run: dotnet build --configuration Release

      # run unit tests
      - name: Run UNIT Tests
        run: |
          dotnet test BPCalcUnit/BPCalcUnitTests.csproj --collect "XPlat Code Coverage"
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"./BPCalcUnit/TestResults/*/coverage.cobertura.xml" -targetdir:"./BPCalcUnit/coverage-report" -reporttypes:Html

      # run BDD acceptance tests
      - name: Run Acceptance Tests
        run: dotnet test BPCalcAcceptance/BPCalcAcceptance.csproj --collect "Code Coverage"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: ./BPCalcUnit/TestResults/

      - name: Upload Coverage Report HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: ./BPCalcUnit/coverage-report/

      - name: Upload BDD Report
        uses: actions/upload-artifact@v4
        with:
          name: bdd-coverage
          path: ./BPCalcAcceptance/TestResults/

      # publish artifact
      - name: dotnet Publish
        run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

      # upload build artifact for deploy job
      - name: Upload artifact for Deployment Job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

  # deploy code to webapp service
  deploy_staging:
    name: Deploy Staging & E2E
    needs: build
    permissions:
      contents: none
    runs-on: windows-latest
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:    
      - uses: actions/checkout@v4

      # download artifact from build job
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # get publishing profile for newly provisioned staging environment
      - name: Get Publish Profile
        run: |
          az webapp deployment list-publishing-credentials --name ${{env.AZURE_WEBAPP_NAME}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{env.AZURE_SUB}} | Tee-Object -Variable PublishProfile
          echo $PublishProfile >>  %GITHUB_ENV%

      # deploy webapp to staging environment
      - name: Deploy to Staging WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          #startup-command: "dotnet BPCalculator.dll"
          publish-profile: ${{ env.PublishProfile }}
          package: .

      # allow app come up for selenium tests
      #- name: Pause
      #  run: sleep 60

      # run selenium e2e tests
      - name: Run Selenium Tests
        run: dotnet test SeleniumTest.dll /Settings:${{ env.E2E_RUN_FILE }} --logger:"html;LogFileName=selenium.html"

      # Upload results of selenium tests
      - uses: actions/upload-artifact@v4
        with:
          name: Selenium Tests Results
          path: TestResults/selenium.html

  # deploy code to webapp service
  deploy_staging_feature:
    name: Deploy Feature to Staging
    needs: deploy_staging
    permissions:
      contents: none
      issues: write
    runs-on: windows-latest
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:    
      - uses: actions/checkout@v4

      # download artifact from build job
      - name: Download Artifact From Build Job
        uses: actions/download-artifact@v4
        with:
          name: .net-app-feature

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # get publishing profile for newly provisioned staging environment
      - name: Get Publish Profile
        run: |
          az webapp deployment list-publishing-credentials --name ${{env.AZURE_WEBAPP_NAME}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{env.AZURE_SUB}} | Tee-Object -Variable PublishProfile
          echo $PublishProfile >>  %GITHUB_ENV%

      # deploy webapp to staging environment
      - name: Deploy Feature to Staging WebApp
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          #startup-command: "dotnet BPCalculator.dll"
          publish-profile: ${{ env.PublishProfile }}
          package: .

  # destroy staging environment
  delete_staging:
    name: Teardown Staging
    needs: deploy_staging_feature
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # manual approval to destroy staging webapp
      - uses: trstringer/manual-approval@v1
        timeout-minutes: 10
        with:
          secret: ${{ github.TOKEN }}
          approvers: nmckeown
          minimum-approvals: 1
          issue-title: "Destroy Staging Env"
          issue-body: "Please approve or deny"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Delete Staging WebApp
        run: az webapp delete --name ${{env.AZURE_STAGING_WEBAPP_NAME}} --resource-group ${{env.AZURE_RESOURCE_GROUP}}
