name: Test Jobs

env:
  AZURE_PROD_WEBAPP_NAME: prod-ca1app               # prod webapp
  AZURE_STAGING_WEBAPP_NAME: staging2-ca1app        # staging webapp
  AZURE_RESOURCE_GROUP: ca1rg
  AZURE_SUB: 9ec68712-3805-4cf9-a4c1-4e5951df302b
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'              # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6'                               # set this to the .NET Core version to use
  URI: https://ca1app.azurewebsites.net/    

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # provision staging environment
  provision_staging:
    name: Provision Staging Infra
    #needs: owasp_dependency_check
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
      - name: Provision Staging
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./IaC/webapp.template.json
          parameters: sites_ca1app_name=${{ env.AZURE_STAGING_WEBAPP_NAME }}

  build:
    name: Build & Test
    runs-on: windows-latest
    needs: provision_staging

    steps:
      - uses: actions/checkout@v4   

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set Up Dependency Caching
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run UNIT Tests
        run: |
          dotnet test BPCalcUnit/BPCalcUnitTests.csproj --collect "XPlat Code Coverage"
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:"./BPCalcUnit/TestResults/*/coverage.cobertura.xml" -targetdir:"./BPCalcUnit/coverage-report" -reporttypes:Html

      - name: Run Acceptance Tests
        run: dotnet test BPCalcAcceptance/BPCalcAcceptance.csproj --collect "Code Coverage"

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: ./BPCalcUnit/TestResults/

      - name: Upload Coverage Report HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html-report
          path: ./BPCalcUnit/coverage-report/

      - name: Upload BDD Report
        uses: actions/upload-artifact@v4
        with:
          name: bdd-coverage
          path: ./BPCalcAcceptance/TestResults/

      - name: dotnet Publish
        run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

  # deploy code to webapp service
  deploy_staging:
    name: Deploy Staging & E2E
    needs: build
    permissions:
      contents: none
    runs-on: windows-latest
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:    
      - uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Publish Profile
        run: az webapp deployment list-publishing-credentials --name ${{env.AZURE_STAGING_WEBAPP_NAME}} --resource-group ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{env.AZURE_SUB}} | Tee-Object -Variable PublishProfile

      - name: Deploy to Staging Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_STAGING_WEBAPP_NAME }}
          #startup-command: "dotnet BPCalculator.dll"
          publish-profile: ${{ $PublishProfile }}
          package: .

      - name: Run Selenium Tests
        run: dotnet test SeleniumTest.dll /Settings:SeleniumTest.runsettings --logger:"html;LogFileName=selenium.html"

      # Upload results of selenium tests
      - uses: actions/upload-artifact@v4
        with:
          name: Selenium Tests Results
          path: TestResults/selenium.html

  delete_staging:
    name: Teardown Staging
    needs: deploy_staging
    runs-on: ubuntu-latest

    steps:
      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Delete Staging WebApp
        run: az webapp delete --name ${{env.AZURE_STAGING_WEBAPP_NAME}} --resource-group ${{env.AZURE_RESOURCE_GROUP}}
